### ISSUE TITLE
SetData(new byte[0]) is ignored

### ISSUE THREAD

**Issue by cameron314** [Sicos1977/CompoundFileStorage#1]
Sometimes it's handy to be able to clear the contents of a stream. I tried to do this via `stream.SetData(new byte[0])`, but eventually, after digging down into the source, I realized [SetStreamData](https://github.com/Sicos1977/CompoundFileStorage/blob/master/CompoundFile.cs#L1919) ignores sets of size 0.

Is this by design? Why allow reading of empty streams but not modification to an empty stream?

**Comment by Sicos1977** [comment]
The reason why this is, is because you can't save an empty stream into a compound file system. There needs to be something in there. It was probably better to raise an error when trying to set an empty stream.

Greetings,
Kees van Spelde

**Comment by cameron314** [comment]
But it's valid for an existing compound file to contain an empty stream -- the ones created by Visual Studio (.suo), for example, have no problem generating such streams.

**Comment by Sicos1977** [comment]
I will have a look into it tomorrow ... if the code still works when settings an empty stream.

**Comment by cameron314** [comment]
Cool, thanks!

**Comment by Sicos1977** [comment]
Sorry that it took a few days to come back on your question... to busy with other things.

I tested the code with stream.SetData(new byte[0])... but that throws an exception.
If I ever find the time I will look into it... but don't expect it to happen soon.

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
Well your in luck... I just tried out something and it seems to work...

Just get the latest code from Github.... it now should work with stream.SetData(new byte[0])

**Comment by cameron314** [comment]
Awesome, thanks :-)
